apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script-configmap
  labels:
    app: my-flask-app
    workspace: scalian-devops-training
data:
  init.sql: |-
    CREATE TABLE favorite_colors (
      name VARCHAR(20),
      color VARCHAR(10)
    );

    INSERT INTO favorite_colors
      (name, color)
    VALUES
      ('Lancelot', 'blue'),
      ('Galahad', 'yellow');